networks:
  # 定义所有服务将连接到的网络。
  federated-network:
    driver: bridge

services:
  # Server服务的完整定义
  server:
    container_name: fl-server
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile.server
    ports:
      - "50051:50051"
    environment:
      - GRPC_SERVER_PORT=50051
    volumes:
      - ../../certs/server:/app/certs:ro
      - ../../logs:/app/logs
      - ../../out:/app/out
    networks:
      - federated-network
    depends_on:
      # server服务应等待aggregator服务准备就绪后再启动。
      - aggregator 

  # 全新的 'aggregator' 服务定义
  aggregator:
    container_name: sgx-aggregator
    build:
      context: ../..
      dockerfile: src/sgx_aggregator/Dockerfile.aggregator
    # aggregator服务需要访问主机的SGX设备。
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
    volumes:
      - "/var/run/aesmd:/var/run/aesmd"
    networks:
      - federated-network 